FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app
COPY pyproject.toml /app/pyproject.toml
COPY ccoli /app/ccoli
COPY server /app/server
RUN pip install --no-cache-dir -e '/app[runtime,test]'

WORKDIR /app
